# Generated by Django 4.2.7 on 2026-01-13 02:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del ingrediente (ej: Harina 0000)', max_length=100, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio por unidad base', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad_base', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('kg', 'Kilogramos'), ('l', 'Litros')], help_text='Unidad de medida base para el precio', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del precio')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad del ingrediente necesaria', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unidad', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('kg', 'Kilogramos'), ('l', 'Litros')], help_text='Unidad de medida para esta cantidad', max_length=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto/postre', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del producto')),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Margen de ganancia en porcentaje (ej: 50.00 para 50%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ingredientes', models.ManyToManyField(help_text='Ingredientes que componen esta receta', through='costos.IngredienteReceta', to='costos.ingrediente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costos.receta'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientereceta',
            unique_together={('receta', 'ingrediente')},
        ),
    ]
